[project]
name = "data-app"
version = "0.1.0"
description = "Data App Description"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "modal>=1.2.4",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "streamlit>=1.52.1",
]
